// <auto-generated />
using GestionDesEtudiants.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionDesEtudiants.Migrations
{
    [DbContext(typeof(EtudiantDbContext))]
    partial class EtudiantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionDesEtudiants.Service.Etudiant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_filiere");

                    b.Property<string>("nom")
                        .IsRequired();

                    b.Property<string>("prenom")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("id_filiere");

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("GestionDesEtudiants.Service.Filiere", b =>
                {
                    b.Property<int>("id_filiere")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nom_filiere");

                    b.HasKey("id_filiere");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("GestionDesEtudiants.Service.Etudiant", b =>
                {
                    b.HasOne("GestionDesEtudiants.Service.Filiere", "filiere")
                        .WithMany("Etudiants")
                        .HasForeignKey("id_filiere")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
